#!/bin/bash

main()
{
  declare s="${1:-.}"

  # We copy everything into another folder
  declare d="$( mktemp -d )/gh-pages"
  mkdir -p "${d}"
  cp -a "${s}/." "${d}"
  cd "${d}"

  # We configure git
  git init
  git config user.name "Travis CI"
  git config user.email "none@none.none"

  # And we push everything to the right branch
  git add .
  git commit -m "Deploy to GitHub Pages"
  git push --force "git@github.com:radium226/mythbuster-apache-spark-talk.git" "master:gh-pages"
}

main "${@}"
